#!/usr/bin/expect
set ip_addr  [lindex $argv 0]  
set user     [lindex $argv 1]  
set passwd   [lindex $argv 2]  
set timeout 30
spawn /usr/bin/ssh-copy-id -i /root/.ssh/id_rsa.pub ${user}@${ip_addr}

expect {
  "yes/no" {send "yes\n";exp_continue}
  "password" {send "${passwd}\n";exp_continue} 
  eof {exit 0;}
}
